src/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [] do
    resources :functions do
      resources :comments, only: %i[create edit update destroy]
      resource :like, only: %i[create destroy]
      resource :save, only: %i[create destroy]
    end
    resources :saves, only: :index
    resource :followerships, only: %i[create destroy]
    get :followerships, action: :index, controller: :followerships
  end

  resource :github, only: [:new]
  resource :session, only: [:destroy]

  resources :notifications, only: %i[show index] do
    post :read_all, as: :read_all, on: :collection
  end
  resources :tags, only: %i[show index]

  get 'timelines/latest', to: 'timelines#latest'
  get 'timelines/liked', to: 'timelines#liked'
  get 'timelines/commented', to: 'timelines#commented'
  get 'timelines/saved', to: 'timelines#saved'
  get 'timelines/contributors', to: 'timelines#contributors'

  root to: 'timelines#latest'
end

src/app/models/function.rb
class Function < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :user_id }, format: { with: /\A[0-9a-z_]+[?!]?\z/i }
  validates :tags, length: { minimum: 0, maximum: 3, message: :maximum_tags_exceeded }
  validates :usage, presence: true
  validates :code, presence: true, code: true
  validates :user, presence: true

  belongs_to :user, counter_cache: true

  before_validation :assign_function_name

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy, as: :likeable
  has_many :saves, dependent: :destroy

  has_many :functions_tags, dependent: :destroy
  has_many :tags, through: :functions_tags

  def tags_list
    tags.map(&:name).join(', ')
  end

  def tags_list=(new_value)
    tag_names = new_value.split(',').reject(&:blank?)
    self.tags = tag_names.map { |name| Tag.find_or_initialize_by(name: name.strip&.downcase) }
  end

  def to_param
    name
  end

  def self.from_param(param)
    find_by(name: param)
  end

  private

  def assign_function_name
    first_function = Code.new(code).functions.first
    self.name = first_function if first_function
  end
end

src/app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  layout 'users', only: %i[index]

  before_action :set_user
  before_action :set_function, only: %i[show edit update destroy]
  before_action :check_permission, only: %i[show edit update destroy]

  LIMIT = 30

  def index
    @function = Function.new(user: @user)
    check_permission

    offset = params.fetch(:offset, 0).to_i
    @functions = @user.functions.limit(LIMIT).offset(offset).order(created_at: :desc).all
    @next = offset + LIMIT if @functions.size == LIMIT
  end

  def show
    @comment = Comment.new(function: @function, user: current_user)
  end

  # GET /functions/new
  def new
    @function = @user.functions.new
    check_permission
  end

  def edit; end

  def create
    @function = @user.functions.new(function_params)
    check_permission

    if @function.save
      redirect_to [@user, @function], notice: 'Function was successfully created.'
    else
      render :new
    end
  end

  def update
    if @function.update(function_params)
      redirect_to [@user, @function], notice: 'Function was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @function.destroy
    redirect_to user_functions_url(@user), notice: 'Function was successfully deleted.'
  end

  private

  def set_user
    @user = User.from_param(params[:user_id]) || raise(ActiveRecord::RecordNotFound)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_function
    @function = @user.functions.from_param(params[:id]) || raise(ActiveRecord::RecordNotFound)
  end

  # Only allow a trusted parameter "white list" through.
  def function_params
    params.require(:function).permit(:usage, :code, :tags_list)
  end

  def check_permission
    raise UnauthorizedException unless can?(@function, action_name.to_sym)
  end
end

src/app/helpers/functions_helper.rb
module FunctionsHelper
  def render_code(ruby)
    formatter = Rouge::Formatters::HTMLInline.new('github')
    formatter = Rouge::Formatters::HTMLLinewise.new(formatter)

    lexer = Rouge::Lexers::Ruby.new
    sanitized = sanitize(formatter.format(lexer.lex(ruby)), tags: %w[div span], attributes: %w[style])
    tag.pre sanitized
  end

  def render_markdown(str)
    options = { input: 'GFM', auto_id_stripping: true, syntax_highlighter: nil }
    allowed_tags = %w[p a ul ol li del strong em blockquote code pre span div]
    allowed_attributes = %w[href rel]

    kramdown_doc = Kramdown::Document.new(str, options)
    sanitize(kramdown_doc.to_html_from_markdown, tags: allowed_tags, attributes: allowed_attributes)
  end
end

src/app/views/functions/_form.html.erb
<%= form_with(model: function, url: [user, function], local: true, html: { class: 'form' }) do |form| %>

  <% if function.errors.any? %>
    <div class="notification is-danger content">
      <%= pluralize(function.errors.count, "error") %> prohibited this function from being saved:

      <ul>
        <% function.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :usage, class: :label %>
    <div class="control"> <%= form.text_area :usage, rows: 5, class: :textarea %> </div>
  </div>

  <div class="field">
    <%= form.label :tags_list, class: :label %>
    <div class="control"> <%= form.text_field :tags_list, class: :input, placeholder: 'Up to 3 tags. Comma seprated.' %> </div>
  </div>

  <div class="field">
    <%= form.label :code, class: :label %>
    <div class="control"> <%= form.text_area :code, rows: 20, class: [:textarea, :codemirror] %> </div>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= form.submit class: 'button is-link' %>
    </div>
  </div>
<% end %>

src/app/views/functions/_function.html.erb
<% full ||= false %>

<div class="card is-shadowless <%= 'is-clipped' unless full %> m-b-md" tabindex="0">
  <header class="card-header is-shadowless">
    <div class="card-header-title">
      <div class="media">
        <div class="media-left">
          <figure class="image is-48x48">
            <%= link_to image_tag(user_image_url(function.user), class: 'is-rounded'), user_functions_path(function.user) %>
          </figure>
        </div>
        <div class="media-content">
          <p class="title is-5">
            <%= link_to function.name, [function.user, function] %>
          </p>
          <p class="subtitle is-6">
            <%= link_to function.user.name, user_functions_path(function.user) %>
            <small class="has-text-grey-light"> · @<%= function.user.username %> · <%= distance_of_time_in_words_to_now function.created_at %></small>
          </p>
        </div>
      </div>
    </div>

  </header>

  <div class="card-content">
    <div class="content">
      <%= render_markdown function.usage %>
    </div>
  </div>

  <%= render_code function.code if full %>

  <div class="card-content has-text-grey-light">
    <small>
      <i class="fas fa-thumbs-up"></i> <%= function.likes.size %> ·
      <i class="fas fa-comment"></i> <%= function.comments.size %> ·
      <i class="fas fa-bookmark"></i> <%= function.saves.size %>
    </small>
    <% unless full %>
      <%= link_to [function.user, function], class: 'button is-pulled-right is-small is-link' do %>
        <span> Show code </span>
        <%= icon('fas fa-code') %>
      <% end %>
    <% end %>
    <div class="is-clearfix"></div>
  </div>

  <%= render 'functions/function_footer', function: function if current_user && full %>
</div>

src/app/views/functions/_function_footer.html.erb
<div class="card-footer">

  <%= link_to_if liked?(function, current_user), icon('fas fa-thumbs-up') + 'Like', user_function_like_path(user_id: function.user, function_id: function), class: 'card-footer-item', method: :delete do  %>
    <%= link_to icon('far fa-thumbs-up') + 'Like', user_function_like_path(user_id: function.user, function_id: function), class: 'card-footer-item has-text-grey', method: :post  %>
  <% end %>

  <%= link_to icon('far fa-comment') + 'Comment', '#comment', class: "card-footer-item"  %>

  <%= link_to_if saved?(function, current_user), icon('fas fa-bookmark') + 'Save',  user_function_save_path(function_id: function, user_id: function.user), method: :delete, class: 'card-footer-item' do %>
    <%= link_to icon('far fa-bookmark') + 'Save', user_function_save_path(function_id: function, user_id: function.user), method: :post , class: 'card-footer-item has-text-grey' %>
  <% end %>

  <%= link_to icon('fas fa-edit') + 'Edit', edit_user_function_path(function.user, function), class: 'card-footer-item' if can?(function, :edit) %>
  <%= link_to icon('fas fa-trash') + 'Delete', [function.user, function], method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-footer-item has-text-danger' if can?(function, :destroy) %>
  <%= link_to icon('far fa-save') + 'Download', user_function_path(function.user, function, format: :rb), class: 'card-footer-item has-text-grey' %>

</div>

src/app/views/functions/_functions.html.erb
<%= render functions %>

<%= link_to 'Load More', user_functions_path(user, offset: @next), remote: true, class: 'button is-fullwidth more' if @next %>

src/app/views/functions/edit.html.erb
<h1 class="title">Editing Function</h1>

<%= render 'form', user: @user, function: @function %>

src/app/views/functions/index.html.erb
<%= content_for :title, @user.name %>

<%= render 'functions', functions: @functions, user: @user %>

<% if @user.functions.empty? %>
  <div class="notification is-success content">
    <%= @user.name %> didn't publish any functions yet.
  </div>
<% end %>

<% if @user.functions.empty? && @user == current_user %>
  <%= render 'common/concept' %>
<% end %>

src/app/views/functions/index.js.erb
var el = document.querySelector('a.more');
var newEl = document.createElement('div');
newEl.innerHTML = '<%= escape_javascript(render 'functions', functions: @functions, user: @user) %>';
el.parentNode.replaceChild(newEl, el);

src/app/views/functions/new.html.erb
<h1 class="title">New Function</h1>

<%= render 'form', user: @user, function: @function %>

src/app/views/functions/show.html.erb
<%= content_for :title, sprintf("%s - by: %s", @function.name, @user.name) %>

<div class="columns">
  <div class="column is-four-fifths">
    <%= render 'tags/tags', tags: @function.tags %>
    <%= render @function, full: true %>
    <%= render @function.comments %>
    <%= render 'comments/form', comment: @comment if can?(@comment, :create) %>
  </div>
  <div class="column">
    <%= render 'recommendations/recommendations', function: @function %>
  </div>
</div>

src/app/views/functions/show.rb.erb
<%= raw @function.usage.lines.map { |line| "# #{line}" }.join %>
<%= raw @function.code %>