src/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [] do
    resources :functions do
      resources :comments, only: %i[create edit update destroy]
      resource :like, only: %i[create destroy]
      resource :save, only: %i[create destroy]
    end
    resources :saves, only: :index
    resource :followerships, only: %i[create destroy]
    get :followerships, action: :index, controller: :followerships
  end

  resource :github, only: [:new]
  resource :session, only: [:destroy]

  resources :notifications, only: %i[show index] do
    post :read_all, as: :read_all, on: :collection
  end
  resources :tags, only: %i[show index]

  get 'timelines/latest', to: 'timelines#latest'
  get 'timelines/liked', to: 'timelines#liked'
  get 'timelines/commented', to: 'timelines#commented'
  get 'timelines/saved', to: 'timelines#saved'
  get 'timelines/contributors', to: 'timelines#contributors'

  root to: 'timelines#latest'
end

src/app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true, format: { with: /\A[0-9a-z_\-]+\z/i }
  validates :github_id, presence: true, uniqueness: true

  has_many :functions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :saves, dependent: :destroy

  has_many :notifications, foreign_key: :recipient_id, inverse_of: :recipient,
                           class_name: 'Notification::Notification', dependent: :destroy

  has_many :following_followerships,
           class_name: :Followership,
           foreign_key: :follower_id,
           inverse_of: :follower,
           dependent: :destroy

  has_many :follower_followerships,
           class_name: :Followership,
           foreign_key: :followee_id,
           inverse_of: :followee,
           dependent: :destroy

  has_many :followees, class_name: :User, through: :following_followerships
  has_many :followers, class_name: :User, through: :follower_followerships

  def to_param
    username
  end

  def self.from_param(username)
    find_by(username: username)
  end

  def self.find_or_create_from_github_user(github_user)
    find_or_create_by!(github_id: github_user['id']) do |new_user|
      username = github_user['login']
      new_user.username = exists?(github_id: username) ? SecureRandom.uuid : username
      new_user.name = github_user['name'] || username
    end
  end
end

src/app/helpers/users_helper.rb
module UsersHelper
  def user_image_url(user)
    "https://avatars0.githubusercontent.com/u/#{user.github_id}?v=4"
  end

  def user_github_url(user)
    "https://github.com/#{user.username}"
  end
end

src/app/views/users/_actions.html.erb
<div class="card m-b-md is-shadowless">
  <div class="card-content">
    <% if current_user && user != current_user %> 
        <%= link_to_if follows?(user), 'Unfollow', user_followerships_path(user), class: 'button is-pulled-right', method: :delete do  %>
           <%= link_to 'Follow', user_followerships_path(user), class: 'button is-pulled-right', method: :post  %>
        <% end %>

        <div class="is-clearfix"></div>
    <% end %>
  </div>
</div>

src/app/views/users/_tabs.html.erb
<div class="tabs">
  <ul>
    <% if current_page?(controller: 'functions', action: 'index')%>
      <li class="is-active">
    <% else %>
      <li>
    <% end %>
    <%= link_to user_functions_path(user), title: 'Published functions' do %>
      Published functions (<%= user.functions.size %>)
    <% end %>
    </li>

    <% if current_page?(controller: 'saves', action: 'index')%>
      <li class="is-active">
    <% else %>
        <li>
    <% end %>
    <%= link_to user_saves_path(user), title: 'Saved functions' do %>
      Saved Functions (<%= user.saves.size %>)
    <% end %>
    </li>


    <% if current_page?(controller: 'followerships', action: 'index', relationship: :followers)%>
      <li class="is-active">
    <% else %>
        <li>
    <% end %>
    <%= link_to user_followerships_path(user, relationship: :followers), title: 'Followers' do %>
      Followers (<%= user.followers.size %>)
    <% end %>
    </li>

    <% if current_page?(controller: 'followerships', action: 'index', relationship: :followees)%>
      <li class="is-active">
    <% else %>
      <li>
    <% end %>
    <%= link_to user_followerships_path(user, relationship: :followees), title: 'Followees' do %>
      Followees (<%= user.followees.size %>)
    <% end %>
    </li>
  </ul>
</div>

src/app/views/users/_user.html.erb
<div class="card m-b-md is-shadowless">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <%= link_to image_tag(user_image_url(user)), user_functions_path(user) %>
        </figure>
      </div>
      <div class="media-content">
        <p>
          <strong> <%= link_to user.name, user_functions_path(user) %> </strong>
          <small>· @<%= user.name %> </small>
        </p>
        <p>
          <%= link_to user_github_url(user), target: '_blank', rel: 'noopener' do %>
            <%= icon('fab fa-github') %> <span>Github</span>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

src/app/views/users/_user_card.html.erb
<div class="card m-b-md">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-128x128">
          <%= image_tag user_image_url(user) %>
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4">
          <%= user.name %>
        </p>
        <p class="subtitle is-6">
          <%= link_to user_github_account_url(user),  target: "_blank" do %>
            @<%= user.username %>
          <% end %>
        </p>
        
        <% unless current_user.nil? || user.id == current_user.id %> 
          <% text = current_user.following?(user.id) ? "Unfollow" : "Follow" %>
          <% method = current_user.following?(user.id) ? :delete : :post %>
          <%= form_with model: current_user.followings.new(followee: user), method: method.to_sym, local: true do |form| %>
            <%= form.hidden_field :followee_id %>
            <%= form.submit text, class: "button has-text" %>
          <% end %>

        <% end %>
      </div>
    </div>
  </div>
</div>