src/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [] do
    resources :functions do
      resources :comments, only: %i[create edit update destroy]
      resource :like, only: %i[create destroy]
      resource :save, only: %i[create destroy]
    end
    resources :saves, only: :index
    resource :followerships, only: %i[create destroy]
    get :followerships, action: :index, controller: :followerships
  end

  resource :github, only: [:new]
  resource :session, only: [:destroy]

  resources :notifications, only: %i[show index] do
    post :read_all, as: :read_all, on: :collection
  end
  resources :tags, only: %i[show index]

  get 'timelines/latest', to: 'timelines#latest'
  get 'timelines/liked', to: 'timelines#liked'
  get 'timelines/commented', to: 'timelines#commented'
  get 'timelines/saved', to: 'timelines#saved'
  get 'timelines/contributors', to: 'timelines#contributors'

  root to: 'timelines#latest'
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/code.rb
class Code
  attr_reader :code

  def initialize(code)
    @code = code.to_s
    @valid = true
    parse_code
  end

  def valid?
    @valid
  end

  def functions
    return [] unless @valid

    @functions ||= extract_functions(@ast)
  end

  private

  def parse_code
    @ast = RubyVM::AbstractSyntaxTree.parse(@code)
  rescue SyntaxError
    @valid = false
  end

  def extract_functions(ast)
    return [] unless ast.is_a?(RubyVM::AbstractSyntaxTree::Node)

    children = ast.children
    return [children.first.to_s] if ast.type == :DEFN

    children.sum do |child|
      extract_functions(child)
    end
  end
end

src/app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user, counter_cache: true
  belongs_to :function, counter_cache: true

  default_scope { order(:created_at) }
end

src/app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: :follower_id, class_name: 'User', inverse_of: :follower_relationships
  belongs_to :following, foreign_key: :following_id, class_name: 'User', inverse_of: :following_relationships
end

src/app/models/followership.rb
class Followership < ApplicationRecord
  belongs_to :follower, class_name: :User
  belongs_to :followee, class_name: :User

  validates :followee, uniqueness: { scope: :follower }
  validate :follower_and_followee

  private

  def follower_and_followee
    errors.add(:follower, :cant_follow_self) if follower == followee
  end
end

src/app/models/function.rb
class Function < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :user_id }, format: { with: /\A[0-9a-z_]+[?!]?\z/i }
  validates :tags, length: { minimum: 0, maximum: 3, message: :maximum_tags_exceeded }
  validates :usage, presence: true
  validates :code, presence: true, code: true
  validates :user, presence: true

  belongs_to :user, counter_cache: true

  before_validation :assign_function_name

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy, as: :likeable
  has_many :saves, dependent: :destroy

  has_many :functions_tags, dependent: :destroy
  has_many :tags, through: :functions_tags

  def tags_list
    tags.map(&:name).join(', ')
  end

  def tags_list=(new_value)
    tag_names = new_value.split(',').reject(&:blank?)
    self.tags = tag_names.map { |name| Tag.find_or_initialize_by(name: name.strip&.downcase) }
  end

  def to_param
    name
  end

  def self.from_param(param)
    find_by(name: param)
  end

  private

  def assign_function_name
    first_function = Code.new(code).functions.first
    self.name = first_function if first_function
  end
end

src/app/models/functions_tag.rb
class FunctionsTag < ApplicationRecord
  belongs_to :function
  belongs_to :tag, counter_cache: true
end

src/app/models/like.rb
class Like < ApplicationRecord
  validates :user, uniqueness: { scope: :likeable }

  belongs_to :likeable, polymorphic: true, counter_cache: true
  belongs_to :user, counter_cache: true
end

src/app/models/notification.rb
module Notification
end

src/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: :User
  belongs_to :followee, class_name: :User

  validates :followee, uniqueness: { scope: :follower }
  validate :follower_and_followee

  private

  def follower_and_followee
    errors.add(:follower, "User Can't Follow Himself") if follower_id == followee_id
  end
end

src/app/models/save.rb
class Save < ApplicationRecord
  validates :function, uniqueness: { scope: :user }

  belongs_to :user, counter_cache: true
  belongs_to :function, counter_cache: true
end

src/app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, uniqueness: true,
                   presence: true,
                   length: { minimum: 3, maximum: 20 },
                   format: { with: /\A[a-z0-9\-]+\z/i }

  has_many :functions_tags, dependent: :destroy
  has_many :functions, through: :functions_tags

  def to_param
    name
  end

  def self.from_param(name)
    find_by(name: name)
  end
end

src/app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true, format: { with: /\A[0-9a-z_\-]+\z/i }
  validates :github_id, presence: true, uniqueness: true

  has_many :functions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :saves, dependent: :destroy

  has_many :notifications, foreign_key: :recipient_id, inverse_of: :recipient,
                           class_name: 'Notification::Notification', dependent: :destroy

  has_many :following_followerships,
           class_name: :Followership,
           foreign_key: :follower_id,
           inverse_of: :follower,
           dependent: :destroy

  has_many :follower_followerships,
           class_name: :Followership,
           foreign_key: :followee_id,
           inverse_of: :followee,
           dependent: :destroy

  has_many :followees, class_name: :User, through: :following_followerships
  has_many :followers, class_name: :User, through: :follower_followerships

  def to_param
    username
  end

  def self.from_param(username)
    find_by(username: username)
  end

  def self.find_or_create_from_github_user(github_user)
    find_or_create_by!(github_id: github_user['id']) do |new_user|
      username = github_user['login']
      new_user.username = exists?(github_id: username) ? SecureRandom.uuid : username
      new_user.name = github_user['name'] || username
    end
  end
end

src/app/helpers/application_helper.rb
module ApplicationHelper
  def title
    if content_for?(:title)
      (content_for :title).prepend('Ruby Functions - ')
    else
      'Ruby Functions'
    end
  end
end

src/app/helpers/elements_helper.rb
module ElementsHelper
  def icon(class_name)
    tag.span tag.i(class: class_name), class: :icon
  end
end

src/app/helpers/functions_helper.rb
module FunctionsHelper
  def render_code(ruby)
    formatter = Rouge::Formatters::HTMLInline.new('github')
    formatter = Rouge::Formatters::HTMLLinewise.new(formatter)

    lexer = Rouge::Lexers::Ruby.new
    sanitized = sanitize(formatter.format(lexer.lex(ruby)), tags: %w[div span], attributes: %w[style])
    tag.pre sanitized
  end

  def render_markdown(str)
    options = { input: 'GFM', auto_id_stripping: true, syntax_highlighter: nil }
    allowed_tags = %w[p a ul ol li del strong em blockquote code pre span div]
    allowed_attributes = %w[href rel]

    kramdown_doc = Kramdown::Document.new(str, options)
    sanitize(kramdown_doc.to_html_from_markdown, tags: allowed_tags, attributes: allowed_attributes)
  end
end

src/app/helpers/likes_helper.rb
module LikesHelper
  def liked?(function, user)
    Like.exists?(user: user, likeable: function)
  end
end

src/app/helpers/saves_helper.rb
module SavesHelper
  def saved?(function, user)
    user.saves.exists?(function: function)
  end
end

src/app/helpers/timelines_helper.rb
module TimelinesHelper
  def achievement(done, label)
    icn = done ? icon('fas fa-check-circle') : icon('far fa-circle')
    tag.li icn + label, class: ('has-text-success' if done)
  end
end

src/app/helpers/users_helper.rb
module UsersHelper
  def user_image_url(user)
    "https://avatars0.githubusercontent.com/u/#{user.github_id}?v=4"
  end

  def user_github_url(user)
    "https://github.com/#{user.username}"
  end
end

src/app/views/common/_concept.html.erb
<div class="hero">
  <div class="hero-body">

    <div class="container has-text-centered">
      <h1 class="title">We're waiting to show off your Ruby creativity.</h1>

      <div class="columns m-t-xl">
        <div class="column">
          <figure class="image container is-128x128">
            <img alt="programming" src="/illustrations/programming.svg"/>
          </figure>
          <div class="subtitle">
            Write one function that is useful for you and others
          </div>
          <p>
            How many times you have been looking for a function that does one
            thing and you end up using a gem just for one function? <br/>

            Here we'll fix that, consider rubyfunctions.com is your repository
            for useful functions, you can get back to it any time <br/>
          </p>
        </div>
        <div class="column">
          <figure class="image container is-128x128">
            <img alt="bibliophile" src="/illustrations/bibliophile.svg"/>
          </figure>
          <div class="subtitle">
            Depend on Ruby standard library and core library only
          </div>

          <p>
            We all have seen the problem with too many dependencies, here we'll
            try to be as minimal as we can, we'll build off of ruby core and
            standard library only, making our functions as independent as possible,
            this means you'll be able to use it any project regardless of its framework
          </p>
        </div>
        <div class="column">
          <figure class="image container is-128x128">
            <img alt="public discussion" src="/illustrations/public_discussion.svg"/>
          </figure>
          <div class="subtitle">
            Show it to others and get feedback
          </div>

          <p>
            Now that you have a useful repository of functions you have wrote,
            show it to other developers, your function maybe useful for other
            people, Also you will get feedback from other developers to improve
            your knowledge, And you'll have the chance to also give feedback to
            others and learn something new from their functions
          </p>
        </div>
      </div>
    </div>

  </div>

src/app/views/layouts/_alert.html.erb
<div class="notification is-danger content">
  <%= Array[alert].join(',') %>
</div>

src/app/views/layouts/_google_tag_manager.html.erb
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','<%= ENV['GOOGLE_TAG_MANAGER'] %>');</script>

src/app/views/layouts/_main.html.erb
<!DOCTYPE html>
<html class="has-navbar-fixed-top">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:image" content="<%= image_url('ogimage.png') %>" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title><%= title %></title>

    <link rel="icon" type="image/png" href="/logo.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <%= javascript_pack_tag 'application' %>
    <%= render 'layouts/google_tag_manager' if ENV.key?('GOOGLE_TAG_MANAGER') %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
      <section class="section">
        <div class="container">
          <%= render 'layouts/notice', notice: notice if notice %>
          <%= render 'layouts/alert', alert: alert if alert %>
          <%= yield %>
        </div>

      </section>
  </body>
</html>

src/app/views/layouts/_navbar.html.erb
<nav class="navbar is-fixed-top">
  <div class="navbar-brand">
    <%= link_to root_path, class: 'navbar-item' do %>
      <%= image_tag 'logo.svg' %>
    <% end %>

    <%= link_to root_path, class: 'navbar-item is-paddingless' do %>
      <strong>RUBY FUNCTIONS</strong>
    <% end %>

    <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-menu" id="navMenu">

    <div class="navbar-end">
      <% if current_user %>
        <div class="navbar-item">

          <div class="media button">
            <div class="media-content">
              <%= link_to current_user.name, user_functions_path(current_user) %>
            </div>
            <div class="media-right">
              <figure class="image is-24x24">
                <%= link_to user_functions_path(current_user) do %>
                  <%= image_tag user_image_url(current_user) %>
                <% end %>
              </figure>
            </div>
          </div>

        </div>
      <% end %>

      <div class="navbar-item">
        <div class="control">

          <% if current_user %>

            <%= link_to notifications_path(state: :unread) , class: 'button is-white' do %>
              <%= icon('far fa-bell') %>
              <% unless unread_notifications(current_user).zero? %>
                <span class="tag is-danger is-small is-rounded"><%= unread_notifications(current_user) %></span>
              <% end %>
            <% end %>

            <%= link_to new_user_function_path(current_user), class: 'button is-link' do %>
              <span>New function</span>
              <%= icon('fas fa-plus') %>
            <% end %>

            <%= link_to icon('fas fa-power-off'), session_path, method: :delete, class: 'button has-text-danger' %>
          <% else %>

            <%= link_to "https://github.com/login/oauth/authorize?client_id=#{ENV["GITHUB_CLIENT_ID"]}", class: 'button' do %>
              <%= icon('fab fa-github') %>
              <span>Login with Github</span>
            <% end %>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</nav>

src/app/views/layouts/_notice.html.erb
<div class="notification is-success content">
  <%= Array[notice].join(',') %>
</div>

src/app/views/layouts/application.html.erb
<%= render 'layouts/main' %>

src/app/views/layouts/users.html.erb
<%= render 'layouts/main' do %>
    <%= render 'users/actions', user: @user if current_user && @user != current_user %>
    <%= render @user %>
    <%= render 'users/tabs', user: @user %>
    <%= yield %>
<% end %>