src/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [] do
    resources :functions do
      resources :comments, only: %i[create edit update destroy]
      resource :like, only: %i[create destroy]
      resource :save, only: %i[create destroy]
    end
    resources :saves, only: :index
    resource :followerships, only: %i[create destroy]
    get :followerships, action: :index, controller: :followerships
  end

  resource :github, only: [:new]
  resource :session, only: [:destroy]

  resources :notifications, only: %i[show index] do
    post :read_all, as: :read_all, on: :collection
  end
  resources :tags, only: %i[show index]

  get 'timelines/latest', to: 'timelines#latest'
  get 'timelines/liked', to: 'timelines#liked'
  get 'timelines/commented', to: 'timelines#commented'
  get 'timelines/saved', to: 'timelines#saved'
  get 'timelines/contributors', to: 'timelines#contributors'

  root to: 'timelines#latest'
end

src/app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  LIMIT = 30

  def latest
    @functions = Function.limit(LIMIT).order(created_at: :desc).all
  end

  def liked
    @functions = Function.limit(LIMIT).order(likes_count: :desc).all
    render :latest
  end

  def commented
    @functions = Function.limit(LIMIT).order(comments_count: :desc).all
    render :latest
  end

  def saved
    @functions = Function.limit(LIMIT).order(saves_count: :desc).all
    render :latest
  end

  def contributors
    @users = User.limit(LIMIT).order(functions_count: :desc).all
  end
end

src/app/helpers/timelines_helper.rb
module TimelinesHelper
  def achievement(done, label)
    icn = done ? icon('fas fa-check-circle') : icon('far fa-circle')
    tag.li icn + label, class: ('has-text-success' if done)
  end
end

src/app/views/timelines/_menu.html.erb
<div class="column is-one-quarter">
  <nav class="panel has-background-white is-shadowless">
    <%= link_to timelines_latest_path, class: ['panel-block', ('is-active' if action_name == 'latest') ] do %>
      <span class="panel-icon">
        <i class="fas fa-clock"></i>
      </span>
      Latest functions
    <% end %>
    <%= link_to timelines_liked_path, class: ['panel-block', ('is-active' if action_name == 'liked') ] do %>
      <span class="panel-icon">
        <i class="fas fa-thumbs-up"></i>
      </span>
      Top liked
    <% end %>
    <%= link_to timelines_commented_path, class: ['panel-block', ('is-active' if action_name == 'commented') ] do %>
      <span class="panel-icon">
        <i class="fas fa-comment"></i>
      </span>
      Top commented
    <% end %>
    <%= link_to timelines_saved_path, class: ['panel-block', ('is-active' if action_name == 'saved') ] do %>
      <span class="panel-icon">
        <i class="fas fa-bookmark"></i>
      </span>
      Top saved
    <% end %>
    <%= link_to timelines_contributors_path, class: ['panel-block', ('is-active' if action_name == 'contributors') ] do %>
      <span class="panel-icon">
        <i class="fas fa-award"></i>
      </span>
      Top contributors
    <% end %>
  </nav>
</div>

src/app/views/timelines/_sidebar.html.erb
<div class="column is-one-quarter">

  <div class="card is-shadowless">

    <div class="card-header">
      <div class="card-header-icon">
        <%= icon('fas fa-trophy') %>
      </div>
      <div class="card-header-title">
        Your next adventures
      </div>
    </div>

    <div class="card-content">
      <img alt="project completed" src="/illustrations/project_completed.svg"/>
      Lets start our journey in ruby functions. The following steps should help your get started.
    </div>

    <div class="card-content">
      <ul>
        <%= achievement(current_user, 'Login with your Github account') %>
        <%= achievement(current_user && !current_user.functions.empty?, 'Publish your first function') %>
        <%= achievement(current_user && current_user.likes.size >= 5, 'Like at least 5 functions') %>
        <%= achievement(current_user && current_user.comments.size >= 5, 'Write at least 5 comments') %>
        <%= achievement(current_user && current_user.saves.size >= 5, 'Save at least 5 functions') %>
        <%= achievement(current_user && current_user.functions.size >= 10, 'Publish 10 functions') %>
      </ul>
    </div>
  </div>

</div>

src/app/views/timelines/contributors.html.erb
<%= render 'common/concept' unless current_user %>

<div class="columns">
  <%= render 'menu'  %>

  <div class="column">
    <%= render @users %>
  </div>

  <%= render 'sidebar' if !current_user || current_user.created_at > 30.days.ago %>
</div>

src/app/views/timelines/latest.html.erb
<%= render 'common/concept' unless current_user %>

<div class="columns">
  <%= render 'menu'  %>

  <div class="column">
    <%= render @functions %>
  </div>

  <%= render 'sidebar' if !current_user || current_user.created_at > 30.days.ago %>
</div>